"use client";

import { useState } from "react";
import { X } from "lucide-react";
import { toast } from "sonner";
import type { PomodoroSettings } from "@/types/entities";
import { usePomodoroMutations } from "../hooks/usePomodoro";

export function SettingsModal({ settings, onClose }: { settings: PomodoroSettings; onClose: () => void }) {
  const mutations = usePomodoroMutations();
  const [form, setForm] = useState({ workSec: Math.round(settings.workSec / 60), shortBreakSec: Math.round(settings.shortBreakSec / 60), longBreakSec: Math.round(settings.longBreakSec / 60), cyclesPerLong: settings.cyclesPerLong, autoCycle: settings.autoCycle, soundEnabled: settings.soundEnabled });
  const save = async () => {
    try { await mutations.updateSettings.mutateAsync({ workSec: form.workSec * 60, shortBreakSec: form.shortBreakSec * 60, longBreakSec: form.longBreakSec * 60, cyclesPerLong: form.cyclesPerLong, autoCycle: form.autoCycle, soundEnabled: form.soundEnabled }); toast.success("¡Listo! Guardamos tu configuración"); onClose(); } catch { toast.error("Ups, no pudimos guardar la configuración. Inténtalo de nuevo."); }
  };
  return <div aria-modal="true" className="fixed inset-0 z-[70] flex items-center justify-center bg-on-surface/20 p-4 backdrop-blur-[1px]" role="dialog"><div className="w-full max-w-md border border-outline-variant bg-surface"><div className="flex items-center justify-between border-b border-outline-variant bg-surface-bright px-5 py-4"><h2 className="font-headline-xs text-headline-xs font-bold text-primary">Configuración Pomodoro</h2><button aria-label="Cerrar" onClick={onClose} type="button"><X size={19} /></button></div><div className="grid grid-cols-1 gap-3 p-5 sm:grid-cols-3">{([['workSec','Trabajo'],['shortBreakSec','Descanso corto'],['longBreakSec','Descanso largo']] as const).map(([key,label]) => <label className="block" key={key}><span className="font-label-caps text-label-caps text-on-surface-variant">{label} (MIN)</span><input className="field mt-1" min={1} onChange={(event) => setForm({ ...form, [key]: Number(event.target.value) || 1 })} type="number" value={form[key]} /></label>)}<label className="block"><span className="font-label-caps text-label-caps text-on-surface-variant">CICLOS</span><input className="field mt-1" min={1} onChange={(event) => setForm({ ...form, cyclesPerLong: Number(event.target.value) || 1 })} type="number" value={form.cyclesPerLong} /></label></div><div className="space-y-3 border-t border-outline-variant px-5 py-4"><label className="flex items-center gap-2 font-body-sm text-body-sm"><input checked={form.autoCycle} onChange={(event) => setForm({ ...form, autoCycle: event.target.checked })} type="checkbox" /> Continuar automáticamente con el descanso</label><label className="flex items-center gap-2 font-body-sm text-body-sm"><input checked={form.soundEnabled} onChange={(event) => setForm({ ...form, soundEnabled: event.target.checked })} type="checkbox" /> Sonido al terminar</label></div><div className="flex justify-end gap-3 border-t border-outline-variant bg-surface-container-low px-5 py-4"><button className="border border-outline-variant px-4 py-2 font-body-sm text-body-sm" onClick={onClose} type="button">Cancelar</button><button className="bg-primary-container px-4 py-2 font-body-sm text-body-sm text-on-primary" onClick={() => void save()} type="button">Guardar</button></div></div></div>;
}
