import { Router } from "express";
import authRoutes from "../modules/auth/auth.routes";
import healthRoutes from "../modules/health/health.routes";
import uploadRoutes from "../modules/uploads/uploads.routes";
import taskRoutes from "../modules/tasks/tasks.routes";
import habitRoutes from "../modules/habits/habits.routes";
import quickNoteRoutes from "../modules/quicknotes/quicknotes.routes";
import pomodoroRoutes from "../modules/pomodoro/pomodoro.routes";
import adminRoutes from "../modules/admin/admin.routes";
import journalRoutes from "../modules/journal/journal.routes";
import knowledgeRoutes from "../modules/knowledge/knowledge.routes";
import pushRoutes from "../modules/push/push.routes";
import reminderRoutes from "../modules/reminders/reminders.routes";
import integrationsRoutes from "../modules/integrations/integration.routes";
import feedbackRoutes from "../modules/feedback/feedback.routes";
import projectRoutes from "../modules/projects/projects.routes";
import timeBlockRoutes from "../modules/timeblocks/timeblocks.routes";
import homeRoutes from "../modules/home/home.routes";
import notificationRoutes from "../modules/notifications/notifications.routes";

const router = Router();
router.use("/auth", authRoutes);
router.use("/health", healthRoutes);
router.use("/uploads", uploadRoutes);
router.use("/tasks", taskRoutes);
router.use("/habits", habitRoutes);
router.use("/quick-notes", quickNoteRoutes);
router.use("/pomodoro", pomodoroRoutes);
router.use("/admin", adminRoutes);
router.use("/journal", journalRoutes);
router.use("/knowledge", knowledgeRoutes);
router.use("/push", pushRoutes);
router.use("/reminders", reminderRoutes);
router.use("/integrations", integrationsRoutes);
router.use("/feedback", feedbackRoutes);
router.use("/projects", projectRoutes);
router.use("/timeblocks", timeBlockRoutes);
router.use("/home", homeRoutes);
router.use("/notifications", notificationRoutes);

export default router;
